<?php
/**
 * See LICENSE.md for license details.
 */
/** @var Magento\Framework\View\Element\Template $block */
?>
<div class="col content">
    <p>
        <?= $block->escapeHtml(__('GLS provides parcel shipping across Germany.')) ?>
    </p>
    <p>
        <?= $block->escapeHtml(__('Furthermore, the GLS  module allows to request shipping labels for incoming orders directly within your Magento suite.')) ?>
    </p>
    <p><?= $block->escapeHtml(__('To get started:')) ?></p>
    <ol>
        <li>
            <em>
                <small>
                    <?= /* @noEscape */ __('If you do not have a GLS account, <a href="https://www.gls.de/" target="_blank">please contact GLS</a> to establish or expand your relationship') ?>
                </small>
            </em>
        </li>
    </ol>
</div>
<div class="col side">
    <aside>
        <div class="section">
            <h3><?= $block->escapeHtml(__('GLS & Magento')) ?></h3>
            <p>
                <?= $block->escapeHtml(__('Having issues configuring the extension? Contact our support desk: ')) ?>
                <a href="mailto:<?= $block->escapeHtml(__('gls.support@netresearch.de'))?>">
                    <?= $block->escapeHtml(__('gls.support@netresearch.de'))?>
                </a>
            </p>
        </div>
    </aside>
</div>
