<?php
/**
 * See LICENSE.md for license details.
 */
/** @var Magento\Framework\View\Element\Template $block */
?>
<div class="col content">
    <p>
        <?= $block->escapeHtml(__('Official GLS plugin for Magento - parcel label creation and checkout integration for several shipping methods.')) ?>
    </p>
    <p>
        <?= $block->escapeHtml(__('Make it easy for your customers and offer them different shipping methods within checkout. The subsequent order processing with GLS parcel label printing can take place directly within your Magento suite. Please note that GLS Shipping is a plugin for customers of GLS Germany GmbH & Co. OHG.')) ?>
    </p>
    <p><?= $block->escapeHtml(__('You are not yet a GLS business customer and would like to receive an individual offer? Simply use the option which is most convenient for you:')) ?></p>
    <ul>
        <li>
            <a href="<?= $block->escapeUrl(__('https://www.gls-pakete.de/en/business-shipping/become-a-business-customer')) ?>" target="_blank">
                <?= $block->escapeHtml(__('Online Form')) ?>
            </a>
        </li>
        <li>
            <a href="mailto:telesales@gls-germany.com">telesales@gls-germany.com</a>
        </li>
        <li>
            <?= $block->escapeHtml(__('+49 (0) 6677 / 646 38 6000 (Mo.–Fr. 8:00 – 17:00 Uhr)')) ?>
        </li>
    </ul>
</div>
<div class="col side">
    <aside>
        <div class="section">
            <h3><?= $block->escapeHtml(__('FAQ & Support')) ?></h3>
            <p>
                <?= $block->escapeHtml(__('If you have issues configuring GLS Shipping, please visit the FAQ and Support Center.')) ?>
                <a href="mailto:gls.m2.extension@gmail.com">gls.m2.extension@gmail.com</a>
            </p>
        </div>
    </aside>
</div>
